imports:
    - { resource: @MetalFranceSiteBundle/Resources/config/image.yml }
    - { resource: @MetalFranceSiteBundle/Resources/config/template_rules.yml }

ezpublish:
    siteaccess:
        # Available siteaccesses
        list:
            - mf_public
            - mf_gestion
        # Siteaccess groups. Use them to group common settings.
        groups:
            metalfrance: [mf_public, mf_gestion]
        default_siteaccess: mf_public
        match:
            Map\Host:
                www.metalfrance.dev: mf_public
                www.metalfrance.net: mf_public
                admin.metalfrance.dev: mf_gestion
                admin.metalfrance.net: mf_gestion

    repositories:
        mf_site: { engine: legacy, connection: default }

    # System settings, grouped by siteaccess and/or siteaccess group
    system:
        metalfrance:
            repository: mf_site
            languages: [fre-FR]
            var_dir: var/metalfrance
            http_cache:
                purge_servers: %http_cache.purge_servers%

            field_templates:
                - { template: "MetalFranceSiteBundle:fields:content_fields.html.twig", priority: 10 }

        mf_public:
            content:
                view_cache: true
                ttl_cache: true
                default_ttl: 3600
            # Define here your image variations (formerly known as "image aliases")
            image_variations:
                my_image_variation:
                    reference: ~
                    filters:
                        - {name: geometry/scaledownonly, params: [400, 350]}
                my_cropped_variation:
                    reference: my_mage_variation
                    filters:
                        - {name: geometry/scalewidthdownonly, params: [300]}
                        - {name: geometry/crop, params: [200, 200, 0, 0]}

        mf_gestion:
            # Use legacy mode to use the admin interface since everything needs to run via the legacy kernel
            legacy_mode: true

twig:
    globals:
        main_site_title: "METAL FRANCE, webzine musique métal"
        meta_tags:
            keywords: "musique, rock, metal, gothique, thrash, punk, tatoo, tatouage, Slipknot, Chimaira, Slayer, Metallica"
            description: "Actus Métal, gothique, Black Metal, Death Metal. Chroniques d'album, live reports, interviews, photos"
            copyright: "Metal France"
            author: "Metal France"
            "og:image": "extension/metalfrance/design/mf/images/image-listing_50x50.png"
        dfp_pub_id: %metalfrance.ad.dfp_pub_id%

assetic:
    bundles: [MetalFranceSiteBundle]

ez_comments:
    system:
        metalfrance:
            default_provider: disqus
            disqus:
                shortname: metalfrance

parameters:
    ezpublish_legacy.metalfrance.view_default_layout: "MetalFranceSiteBundle::pagelayout.html.twig"
    ezpublish_legacy.metalfrance.module_default_layout: "MetalFranceSiteBundle::pagelayout_legacy.html.twig"
