services:
    metalfrance.fieldType.xrowmetadata:
        class: %ezpublish.fieldType.eznull.class%
        parent: ezpublish.fieldType
        arguments: [ "xrowmetadata" ]
        tags:
            - {name: ezpublish.fieldType, alias: xrowmetadata}

    metalfrance.fieldType.xrowmetadata.converter:
        class: %ezpublish.fieldType.eznull.converter.class%
        tags:
            - {name: ezpublish.storageEngine.legacy.converter, alias: xrowmetadata, lazy: true, callback: '::create'}
