services:
    metalfrance.fieldType.xrowmetadata:
        class: %ezpublish.fieldType.eznull.class%
        parent: ezpublish.fieldType
        arguments: [ "xrowmetadata" ]
        tags:
            - {name: ezpublish.fieldType, alias: xrowmetadata}

    metalfrance.fieldType.objectrelationbrowse:
        class: %ezpublish.fieldType.eznull.class%
        parent: ezpublish.fieldType
        arguments: [ "ezobjectrelationbrowse" ]
        tags:
            - {name: ezpublish.fieldType, alias: ezobjectrelationbrowse}

    metalfrance.fieldType.jvamazonid:
        class: %ezpublish.fieldType.eznull.class%
        parent: ezpublish.fieldType
        arguments: [ "jvamazonid" ]
        tags:
            - {name: ezpublish.fieldType, alias: jvamazonid}

    metalfrance.fieldType.recaptcha:
        class: %ezpublish.fieldType.eznull.class%
        parent: ezpublish.fieldType
        arguments: [ "recaptcha" ]
        tags:
            - {name: ezpublish.fieldType, alias: recaptcha}

    metalfrance.fieldType.eztags:
        class: %ezpublish.fieldType.eznull.class%
        parent: ezpublish.fieldType
        arguments: [ "eztags" ]
        tags:
            - {name: ezpublish.fieldType, alias: eztags}

    metalfrance.fieldType.null.converter:
        class: %ezpublish.fieldType.eznull.converter.class%
        tags:
            - {name: ezpublish.storageEngine.legacy.converter, alias: xrowmetadata, lazy: true, callback: '::create'}
            - {name: ezpublish.storageEngine.legacy.converter, alias: ezobjectrelationbrowse, lazy: true, callback: '::create'}
            - {name: ezpublish.storageEngine.legacy.converter, alias: jvamazonid, lazy: true, callback: '::create'}
            - {name: ezpublish.storageEngine.legacy.converter, alias: recaptcha, lazy: true, callback: '::create'}
            - {name: ezpublish.storageEngine.legacy.converter, alias: eztags, lazy: true, callback: '::create'}
