parameters:
    # Advertisement
    metalfrance.ad.dfp_pub_id: "ca-pub-6334451484838012"

    # Analytics
    metalfrance.analytics.google_account: "UA-5064419-1"
    metalfrance.analytics.domain: ".metalfrance.net"
    metalfrance.analytics.category_by_contenttype:
        mf_chronique_cd: "Chroniques"
        mf_gallerie: "Photos"
        mf_interview: "Interviews"
        mf_livereport: "LiveReports"
        mf_page_livereport: "LiveReports"
        mf_blog: "News"
        mf_blog_post: "News"
        mf_concert_francebillet: "Concerts"
        frontpage: "Home"

    # Location settings
    # Override those in config_<env>.yml if dev diverges from prod.
    metalfrance.location_settings:
        reviews: 91
        agenda: 12701
        news: 1158
        liveReports: 1011
        interviews: 12435
        photos: 8854
