parameters:
    # Advertisement
    metalfrance.ad.dfp_pub_id: "ca-pub-6334451484838012"

    # Analytics
    metalfrance.analytics.google_account: "UA-5064419-1"
    metalfrance.analytics.domain: ".metalfrance.net"
    metalfrance.analytics.category_by_contenttype:
        mf_chronique_cd: "Chroniques"
        mf_gallerie: "Photos"
        mf_interview: "Interviews"
        mf_livereport: "LiveReports"
        mf_page_livereport: "LiveReports"
        blog: "News"
        blog_post: "News"
        mf_concert_francebillet: "Concerts"
        frontpage: "Home"

    # Location settings
    # Override those in config_<env>.yml if dev diverges from prod.
    metalfrance.location_settings:
        reviews: %metalfrance.location_setttings.reviews%
        agenda: %metalfrance.location_setttings.agenda%
        news: %metalfrance.location_setttings.news%
        liveReports: %metalfrance.location_setttings.liveReports%
        interviews: %metalfrance.location_setttings.interviews%
        photos: %metalfrance.location_setttings.photos%
        contact: %metalfrance.location_setttings.contact%
        footer: %metalfrance.location_setttings.footer%

    metalfrance.links:
        forum: "http://forum.metalfrance.net"
        twitter: "http://twitter.com/metalfrance"
        facebook: "https://www.facebook.com/MetalFrance"

    # Sidebar
    metalfrance.sidebar.default_blocks: [agenda, rss, facebook]

    # Lists settings
    metalfrance.default.news.list_limit: 15
    metalfrance.default.gallery.list_limit: 12
    metalfrance.default.review.list_limit: 6

    metalfrance.default.gmaps_key: ~
