parameters:
    # Advertisement
    metalfrance.ad.dfp_pub_id: "ca-pub-6334451484838012"

    # Analytics
    metalfrance.analytics.google_account: "UA-5064419-1"
    metalfrance.analytics.domain: ".metalfrance.net"
