parameters:
    metalfrance.analytics.class: MetalFrance\SiteBundle\Utils\AnalyticsService
    metalfrance.twig.legacy_extension.class: MetalFrance\SiteBundle\Twig\MetalFranceLegacyExtension
    metalfrance.repository.layout.class: MetalFrance\SiteBundle\Repository\LayoutRepository
    metalfrance.repository.news.class: MetalFrance\SiteBundle\Repository\NewsRepository
    metalfrance.repository.gallery.class: MetalFrance\SiteBundle\Repository\GalleryRepository
    metalfrance.repository.review.class: MetalFrance\SiteBundle\Repository\ReviewRepository
    metalfrance.pagerfanta.view.class: MetalFrance\SiteBundle\Pagerfanta\View\MetalFranceView

services:
    metalfrance.analytics:
        class: %metalfrance.analytics.class%
        arguments: [%metalfrance.analytics.category_by_contenttype%, @ezpublish.api.service.location, @ezpublish.api.service.content_type]

    metalfrance.twig.legacy_extension:
        class: %metalfrance.twig.legacy_extension.class%
        arguments: [@ezpublish_legacy.kernel]
        tags:
            - {name: twig.extension}

    metalfrance.repository.layout:
        class: %metalfrance.repository.layout.class%
        arguments: [@ezpublish.api.service.content, @ezpublish.api.service.location, %metalfrance.location_settings%]

    metalfrance.repository.news:
        class: %metalfrance.repository.news.class%
        arguments: [%metalfrance.location_settings%]

    metalfrance.repository.gallery:
        class: %metalfrance.repository.gallery.class%
        arguments: [%metalfrance.location_settings%, @ezpublish.api.service.search]

    metalfrance.repository.review:
        class: %metalfrance.repository.review.class%
        arguments: [%metalfrance.location_settings%]

    metalfrance.pagerfanta.view:
        class: %metalfrance.pagerfanta.view.class%
        tags:
            - { name: pagerfanta.view, alias: metalfrance }

    metalfrance.pagerfanta.translated_view:
        class: WhiteOctober\PagerfantaBundle\View\TwitterBootstrapTranslatedView
        arguments: [@metalfrance.pagerfanta.view, @translator]
        tags:
            - { name: pagerfanta.view, alias: metalfrance_translated }
