parameters:
    metalfrance.analytics.category_by_contenttype:
        mf_chronique_cd: "Chroniques"
        mf_gallerie: "Photos"
        mf_interview: "Interviews"
        mf_livereport: "LiveReports"
        mf_page_livereport: "LiveReports"
        mf_blog: "News"
        mf_blog_post: "News"
        mf_concert_francebillet: "Concerts"
        frontpage: "Home"
    metalfrance.analytics.class: MetalFrance\SiteBundle\Utils\AnalyticsService

services:
    metalfrance.analytics:
        class: %metalfrance.analytics.class%
        arguments: [%metalfrance.analytics.category_by_contenttype%]
