ezpublish:
    system:
        metalfrance:
            location_view:
                full:
                    blog:
                        controller: "MetalFranceSiteBundle:Blog:listBlogPosts"
                        template: "MetalFranceSiteBundle:full:blog.html.twig"
                        match:
                            Identifier\ContentType: blog

                    blog_post:
                        controller: "MetalFranceSiteBundle:Blog:showBlogPost"
                        template: "MetalFranceSiteBundle:full:blog_post.html.twig"
                        match:
                            Identifier\ContentType: blog_post

                carrousel:
                    blog_post:
                        template: "MetalFranceSiteBundle:carrousel:blog_post.html.twig"
                        match:
                            Identifier\ContentType: blog_post

                line:
                    blog_post:
                        template: "MetalFranceSiteBundle:line:blog_post.html.twig"
                        match:
                            Identifier\ContentType: blog_post
