ezpublish:
    system:
        metalfrance:
            location_view:
                full:
                    blog:
                        controller: "MetalFranceSiteBundle:Blog:listBlogPosts"
                        template: "MetalFranceSiteBundle:full:blog.html.twig"
                        match:
                            Identifier\ContentType: blog

                    blog_post:
                        controller: "MetalFranceSiteBundle:Blog:showBlogPost"
                        template: "MetalFranceSiteBundle:full:blog_post.html.twig"
                        match:
                            Identifier\ContentType: blog_post

                    gallery_list:
                        controller: "MetalFranceSiteBundle:Gallery:listGalleries"
                        template: "MetalFranceSiteBundle:full:gallery_list.html.twig"
                        match:
                            Id\Location: %metalfrance.location_setttings.photos%

                    gallery:
                        controller: "MetalFranceSiteBundle:Gallery:showGallery"
                        template: "MetalFranceSiteBundle:full:gallery.html.twig"
                        match:
                            Identifier\ContentType: mf_gallerie

                    review_list:
                        controller: "MetalFranceSiteBundle:Review:listReviews"
                        template: "MetalFranceSiteBundle:full:review_list.html.twig"
                        match:
                            Id\Location: %metalfrance.location_setttings.reviews%

                carrousel:
                    blog_post:
                        template: "MetalFranceSiteBundle:carrousel:blog_post.html.twig"
                        match:
                            Identifier\ContentType: blog_post

                line:
                    blog_post:
                        template: "MetalFranceSiteBundle:line:blog_post.html.twig"
                        match:
                            Identifier\ContentType: blog_post

                    gallery:
                        controller: "MetalFranceSiteBundle:Gallery:showGallery"
                        template: "MetalFranceSiteBundle:line:gallery.html.twig"
                        match:
                            Identifier\ContentType: mf_gallerie
