imports:
    - {resource: @MetalFranceSiteBundle/Resources/config/mf.yml}
    - {resource: @MetalFranceSiteBundle/Resources/config/ezpublish.yml}

ezpublish:
    http_cache:
        purge_type: %http_cache.purge_type%

    imagemagick:
        enabled: true
        path: %imagemagick_path%

stash:
    caches:
        default:
            drivers:
                - FileSystem
            inMemory: true
            registerDoctrineAdapter: false

ez_publish_legacy:
    enabled: true
    root_dir: %kernel.root_dir%/../ezpublish_legacy
