imports:
    - {resource: @MetalFranceSiteBundle/Resources/config/mf.yml}
    - {resource: @MetalFranceSiteBundle/Resources/config/image.yml}

ezpublish:
    http_cache:
        purge_type: local

    imagemagick:
        enabled: true
        path: %imagemagick_path%

stash:
    caches:
        default:
            handlers:
                - FileSystem
            inMemory: true
            registerDoctrineAdapter: false
