parameters:
#    metal_france_legacy.example.class: MetalFrance\LegacyBundle\Example

services:
#    metal_france_legacy.example:
#        class: %metal_france_legacy.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
